services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm run dev
    envVars:
      - key: NODE_ENV
        value: production
 