services:
  - type: web
    name: chat-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_SOCKET_URL
        value: wss://chat-backend-j81w.onrender.com
    healthCheckPath: /
    autoDeploy: true
 